"""add google_id, nullable hashed_password, oauth handoff codes table

Revision ID: 647324fe3116
Revises: 8f893c864c1a
Create Date: 2026-09-07 05:30:35.152856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647324fe3116'
down_revision: Union[str, None] = '8f893c864c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_handoff_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_handoff_codes_code_hash'), 'oauth_handoff_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_oauth_handoff_codes_user_id'), 'oauth_handoff_codes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_oauth_handoff_codes_user_id'), table_name='oauth_handoff_codes')
    op.drop_index(op.f('ix_oauth_handoff_codes_code_hash'), table_name='oauth_handoff_codes')
    op.drop_table('oauth_handoff_codes')
    # ### end Alembic commands ###
